### PR TITLE
FAQ.md

### PR DESCRIPTION
**Pull request by amusanmikel**
I have created a new FAQ for this lovely application, kindly check and merge.

### CODE REVIEW

**Comment by ramack** [comment]
you created the RP against and merged it into your own repository. Was that intended? Or did you want to create the RP against the main repo of ActivityDiary? -> then just give it another try and find out how it works...

**Review by ramack — COMMENTED** [review]
First of all thanks for your willingness to contribute. I really appreciate it!

I personally am not a friend of filename with spaces and special characters like "("... as FAQ is widely known, what about just naming it faq?

And what about the format? Text is nice and content counts more than form, and I personally would even prefer plain text. Nevertheless we are now in a colored world and I am not the target audience of that file, I guess,  so maybe we should make this more visible in the long run. I see the options:
- Markdown, as it would be nicely rendered by github while still be readable text
- HTML, which we could include in a full web page for the app, but it seems to make most sense if we do that directly... are you interested in creating something?

Edit: even with markdown we could include it in a webpage, as I have a PHP-ready server available and there are markdown parsers in PHP around...

**Comment by ramack** [comment]
and yet another thing...
There is a [ticket about creating an FAQ in the github tracker](https://github.com/ramack/ActivityDiary/issues/133), where @olayhemy suggested to provide an FAQ, maybe the two of you can join forces?

**Comment by amusanmikel** [comment]
Hi
Sorry for the troubles, which would you prefer now, a markdown or html for
the FAQ?.
Thanks

**Comment by amusanmikel** [comment]
I am waiting for your reply sir

**Comment by ramack** [comment]
I try to be fast, and sometimes it works, but you cannot expect an instant reaction, sorry.

About the topics, I try to suggest options to give you the freedom to choose. If you decide to make a PR against my repository and I don't have a strong reason I will merge it. - Even if it is just a text file as it is now. It is definitely better to have that than nothing, but if you want to do a full website and publicity campaign it would also be good. So it's up to you how far you wanna go.

I probably would do it as markdown for now, as it is directly rendered nicely with the existing infrastructure, and also later it can be included - and if a reformatting is necessary, we always can do it when really needed. - Or when someone decides it is important for him/her. -> yet another lesson about free software and collaborative projects: The things that are important for someone will be done. And I strongly recommend, that you do what is fun for you or what you consider important. Because this is what brings you forward and improves the project in the way you'd like it to be improved. Collaborative project are also a very good area to learn, try things out and practice in the full range from social interaction over website design, GUI programming or deep learning algorithms. Just choose and start.

One more thing about your wording: I personally don't feel comfortable if you call me sir. I am no way better or more important than you, and "sir" is somehow a way how you call someone standing above - which I really don't want to be your way of thinking.

**Pull request merged**
